version: 2

sources:
  - name: data
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: Dataset con todos los productos
      - name: sales
        identifier: raw_gz_sales
        description: Dataset con la información de las ventas
      - name: ship
        identifier: raw_gz_ship
        description: Dataset con la información de logística
      - name: adwords
        identifier: raw_gz_adwords
        description: Adwords campaign data
      - name: bing
        identifier: raw_gz_bing
        description: Bing campaign data
      - name: criteo
        identifier: raw_gz_criteo
        description: Criteo campaign data
      - name: facebook
        identifier: raw_gz_facebook
        description: Facebook campaign data

              


          