version: 2

sources:
  - name: data
    schema: gz_raw_data
    tables:
      - name: product
        identifier: raw_gz_product
        description: Dataset con todos los productos
      - name: sales
        identifier: raw_gz_sales
        description: Dataset con la información de las ventas
      - name: ship
        identifier: raw_gz_ship
        description: Dataset con la información de logística

models:
  - name: product
    description: Modelo de producto
    columns:
      - name: products_id
        description: Primary key
        tests:
          - unique
          - not_null
      - name: purchase_price
        description: Costo de compra
        tests:
          - not_null
      - name: sales
        description: Modelo de ventas
        columns:
          - name: products_id
            tests:
              - unique
              


          